version: '3.8'
services:
  app:
    image: duongngo21/timelypm:latest
    container_name: timelypm
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
