name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # hoặc branch bạn muốn trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image
      run: |
        docker build -t tranquoccuong/timelypm-be:latest .
        docker push tranquoccuong/timelypm-be:latest

    - name: Deploy on remote server via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          docker pull tranquoccuong/timelypm-be:latest
          docker stop timelypm-be || true && docker rm timelypm-be || true
          docker run -d --name timelypm-be -p 8080:8080 tranquoccuong/timelypm-be:latest
