name: CI/CD for TimelyPM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for mvnw
      run: chmod +x ./mvnw

    - name: Build Spring Boot JAR
      run: ./mvnw clean package

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t tranquoccuong/timelypm-be:latest .

    - name: Push image to Docker Hub
      run: docker push tranquoccuong/timelypm-be:latest

    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v1.0.3
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          if ! command -v docker &> /dev/null; then
            echo "Docker not found. Installing Docker..."
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker $USER
          fi

          if ! command -v docker-compose &> /dev/null; then
            echo "Docker Compose not found. Please install it manually."
            exit 1
          fi

          cd ~/tranquoccuong

          cat <<EOF > ~/tranquoccuong/docker-compose.yml
          version: '3.8'
          services:
            app:
              image: tranquoccuong/timelypm-be:latest
              container_name: TimelyPM
              ports:
                - "8080:8080"
              environment:
                - SPRING_PROFILES_ACTIVE=prod
              restart: always
          EOF

          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

          docker pull tranquoccuong/timelypm-be:latest
          docker-compose down
          docker-compose up -d
